package me.nosmastew.deadsociety.configuration;

import me.nosmastew.deadsociety.DeadSociety;
import org.bukkit.OfflinePlayer;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

public class UserData extends YamlConfiguration {

    private static final Map<OfflinePlayer, UserData> configs = new HashMap<>();

    public static UserData getConfig(DeadSociety plugin, OfflinePlayer player) {
        synchronized (configs) {
            return configs.computeIfAbsent(player, k -> new UserData(plugin, player));
        }
    }

    public static void remove(OfflinePlayer player) {
        configs.remove(player);
    }

    public static void removeAll() {
        synchronized (configs) {
            configs.clear();
        }
    }

    private final File file;
    private final Object saveLock = new Object();
    private final OfflinePlayer player;

    private UserData(DeadSociety plugin, OfflinePlayer player) {
        super();
        this.player = player;
        this.file = new File(plugin.getDataFolder(),
                "userdata" + File.separator + player.getUniqueId() + ".yml");
        reload();
    }

    public OfflinePlayer getPlayer() {
        return player;
    }

    private void reload() {
        synchronized (saveLock) {
            try {
                load(file);
            } catch (Exception ignore) {
            }
        }
    }

    public void save() {
        synchronized (saveLock) {
            try {
                save(file);
            } catch (Exception ignore) {
            }
        }
    }

    public void setAccountInfo() {
        String header = "WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE.";
        if (options().header() == null) options().header(header);

        set("last-account-name", player.getName());
        set("local-chat", true);

        save();
    }
}