package me.nosmastew.deadsociety.configuration;

import me.nosmastew.deadsociety.DeadSociety;
import org.bukkit.Location;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

public class ZoneData extends YamlConfiguration {

    private static final Map<String, ZoneData> configs = new HashMap<>();

    public static ZoneData getConfig(DeadSociety plugin, String zone) {
        synchronized (configs) {
            return configs.computeIfAbsent(zone, k -> new ZoneData(plugin, zone));
        }
    }

    public static void remove(String zone) {
        configs.remove(zone);
    }

    public static void removeAll() {
        synchronized (configs) {
            configs.clear();
        }
    }

    private final File file;
    private final Object saveLock = new Object();

    private ZoneData(DeadSociety plugin, String zone) {
        super();
        this.file = new File(plugin.getDataFolder(),
                "zones" + File.separator + zone + ".yml");
        reload();
    }

    private void reload() {
        synchronized (saveLock) {
            try {
                load(file);
            } catch (Exception ignore) {
            }
        }
    }

    public void save() {
        synchronized (saveLock) {
            try {
                save(file);
            } catch (Exception ignore) {
            }
        }
    }

    public void create(String zone, Location location){
        String header = "WARNING: THIS FILE IS AUTOMATICALLY GENERATED. If you modify this file by hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE.";
        if (options().header() == null) options().header(header);
        set("zone.type", zone);
        set("zone.spawn", location);
        save();
    }
}